name=input("Enter your name")
branch=input("enter your branch")
gender=input("Enetr your gender")
college=input("enetr colege")
age=int(input("Enetr your age"))
print("Name",name)
print("Branch",branch)
print("Gender",gender)
print("College",college)
print("Age",age)
